"use client"

import { useEffect, useMemo, useState } from "react"
import { Activity, AlertTriangle, ArrowUpRight, BarChart3, Bell, ChevronDown, ClipboardList, Factory, Gauge, Layers3, Menu, PackageCheck, Play, Settings2, Sparkles, Target, Timer, Truck, X } from "lucide-react"

type Resource = { id: string; name: string; kind: "weld" | "silicone"; cycle: number; available: number; machines: number; setup?: number; initial?: number; min?: number; max?: number }
type PN = { pn: string; desc: string; demand: number; machine: "600k" | "1M"; weld: number; silicone: number; min: number; max: number; stock: number; priority: number; active: boolean }
type Order = { no: number; pn: string; machine: string; qty: number; start: string; end: string; setup: number; served: number; remaining: number; before: number; after: number; coverage: number }
type Result = { orders: Order[]; metrics: Record<string, number | string>; alerts: string[]; bufferData: { time: string; m600: number; m1m: number; total: number }[] }

const defaultResources: Resource[] = [
  { id: "weld", name: "Máquina de Solda por Feixe de Elétrons", kind: "weld", available: 720, cycle: 42, setup: 10, machines: 1 },
  { id: "600k", name: "Máquina de Silicone 600.000 mm²/s", kind: "silicone", available: 720, cycle: 150, machines: 1, initial: 36, min: 18, max: 72 },
  { id: "1M", name: "Máquina de Silicone 1.000.000 mm²/s", kind: "silicone", available: 720, cycle: 210, machines: 1, initial: 24, min: 12, max: 48 },
]
const defaultPNs: PN[] = [
  { pn: "DM-401", desc: "Damper dianteiro", demand: 480, machine: "600k", weld: 42, silicone: 150, min: 24, max: 72, stock: 48, priority: 1, active: true },
  { pn: "DM-402", desc: "Damper lateral A", demand: 360, machine: "600k", weld: 36, silicone: 120, min: 18, max: 60, stock: 36, priority: 2, active: true },
  { pn: "DM-501", desc: "Damper traseiro", demand: 160, machine: "1M", weld: 28, silicone: 250, min: 12, max: 36, stock: 26, priority: 1, active: true },
]
const read = <T,>(key: string, fallback: T) => { if (typeof window === "undefined") return fallback; try { return JSON.parse(localStorage.getItem(key) || "null") || fallback } catch { return fallback } }
const timeLabel = (minutes: number, start: string) => { const [h, m] = start.split(":").map(Number); const totalSeconds = Math.round((h * 60 + m + minutes) * 60); const totalMinutes = Math.floor(totalSeconds / 60); const seconds = totalSeconds % 60; return `${String(Math.floor(totalMinutes / 60) % 24).padStart(2, "0")}:${String(totalMinutes % 60).padStart(2, "0")}${seconds ? `:${String(seconds).padStart(2, "0")}` : ""}` }

function Metric({ label, value, unit, icon: Icon, tone = "cyan" }: { label: string; value: string; unit?: string; icon: any; tone?: string }) { return <div className="metric"><div className="metric-top"><span className={`metric-icon ${tone}`}><Icon /></span></div><div className="metric-value">{value}<small>{unit}</small></div><div className="metric-label">{label}</div></div> }
function Section({ title, subtitle, children, action }: { title: string; subtitle?: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="panel"><div className="section-head"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>{children}</section> }
function Field({ label, value, onChange, type = "number", options }: { label: string; value: string | number; onChange: (v: string) => void; type?: string; options?: string[] }) { return <label className="field"><span>{label}</span>{options ? <select value={value} onChange={e => onChange(e.target.value)}>{options.map(o => <option key={o}>{o}</option>)}</select> : <input type={type} value={value} onChange={e => onChange(e.target.value)} />}</label> }

export default function Home() {
  const [active, setActive] = useState("Dashboard"); const [open, setOpen] = useState(false); const [resources, setResources] = useState<Resource[]>(defaultResources); const [pns, setPns] = useState<PN[]>(defaultPNs); const [result, setResult] = useState<Result | null>(null)
  useEffect(() => { setResources(read("damper-resources", defaultResources)); setPns(read("damper-pns", defaultPNs)); setResult(read("damper-last-result", null)) }, [])
  useEffect(() => { localStorage.setItem("damper-resources", JSON.stringify(resources)) }, [resources]); useEffect(() => { localStorage.setItem("damper-pns", JSON.stringify(pns)) }, [pns])
  const nav = [["Dashboard", BarChart3], ["Simulação", Timer], ["Otimização", Sparkles], ["Cadastro de PNs", ClipboardList], ["Recursos", Factory]] as const
  return <div className="app-shell"><aside className={open ? "sidebar open" : "sidebar"}><div className="brand"><div className="brand-mark"><Activity /></div><div><strong>DamperFlow</strong><span>OPTIMIZER</span></div><button className="close-mobile" onClick={() => setOpen(false)}><X /></button></div><div className="workspace"><span>PLANTA INDUSTRIAL</span><button>BR-SP-01 <ChevronDown /></button></div><nav>{nav.map(([name, Icon]) => <button key={name} className={active === name ? "nav-item active" : "nav-item"} onClick={() => { setActive(name); setOpen(false) }}><Icon />{name}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Settings2 />Configurações</button><div className="profile"><div className="avatar">AR</div><div><strong>André Rodrigues</strong><span>Planejamento</span></div></div></div></aside><main className="main"><header><button className="menu" onClick={() => setOpen(true)}><Menu /></button><div><div className="eyebrow">CONTROLE DE PRODUÇÃO <span className="live"><i /> sistema online</span></div><h1>{active}</h1></div><div className="header-actions"><button className="icon-button"><Bell /></button><button className="date-button">Hoje, 26 set 2026 <ChevronDown /></button></div></header>{active === "Dashboard" && <Dashboard result={result} onSimulation={() => setActive("Simulação")} />}{active === "Simulação" && <Simulation resources={resources} pns={pns} result={result} setResult={setResult} />}{active === "Cadastro de PNs" && <Registry pns={pns} setPns={setPns} />}{active === "Recursos" && <Resources resources={resources} setResources={setResources} />}{active === "Otimização" && <Simulation resources={resources} pns={pns} result={result} setResult={setResult} />}</main></div>
}

function Dashboard({ result, onSimulation }: { result: Result | null; onSimulation: () => void }) { const m = result?.metrics; return <div className="page-content"><div className="intro"><div><p className="eyebrow">VISÃO GERAL · ÚLTIMO RESULTADO</p><h2>{result ? "Operação calculada." : "Aguardando sua primeira simulação."}</h2><p className="muted">{result ? "Indicadores calculados exclusivamente com os dados cadastrados." : "Cadastre os recursos e os PNs e execute uma simulação para gerar os indicadores."}</p></div><button className="outline-button" onClick={onSimulation}><Play /> Abrir simulação <ArrowUpRight /></button></div>{!result ? <Section title="Sem resultados" subtitle="O Dashboard será preenchido após a execução"><div className="empty-state"><Target /><strong>Nenhuma simulação executada</strong><span>Configure os dados mestres e execute o turno para visualizar capacidade, buffers, gargalos e recomendações.</span></div></Section> : <><div className="metrics"><Metric label="Buffer médio" value={String(m?.avgBuffer)} unit=" peças" icon={Layers3} /><Metric label="Buffer máximo" value={String(m?.maxBuffer)} unit=" peças" icon={PackageCheck} tone="green" /><Metric label="Lead time" value={String(m?.leadTime)} unit=" min" icon={Gauge} tone="amber" /><Metric label="Utilização da solda" value={String(m?.weldUtil)} unit="%" icon={Factory} tone="purple" /></div><div className="recommendation-strip"><div><span className="strip-icon"><Target /></span><div><small>GARGALO DO SISTEMA</small><strong>{m?.bottleneck}</strong></div></div><div><span className="strip-icon amber"><Truck /></span><div><small>DEMANDA NÃO ATENDIDA</small><strong>{m?.unmet} peças</strong></div></div><div className="strip-action"><button onClick={onSimulation}>Ver sequência <ArrowUpRight /></button></div></div><Section title="Alertas da simulação"><div className="alerts">{result.alerts.length ? result.alerts.map(a => <div className="alert" key={a}><AlertTriangle />{a}</div>) : <div className="alert success">Nenhum alerta identificado no turno.</div>}</div></Section></>}</div> }

function Simulation({ resources, pns, result, setResult }: { resources: Resource[]; pns: PN[]; result: Result | null; setResult: (r: Result | null) => void }) { const [duration, setDuration] = useState(720); const [start, setStart] = useState("06:00"); const [interval, setInterval] = useState(15); const [strategy, setStrategy] = useState("Menor cobertura primeiro"); const run = () => { const weld = resources.find(r => r.kind === "weld")!; const sil = resources.filter(r => r.kind === "silicone"); const buffers: Record<string, number> = Object.fromEntries(sil.map(r => [r.id, r.initial || 0])); const remaining: Record<string, number> = Object.fromEntries(pns.map(p => [p.pn, p.demand])); const orders: Order[] = []; const bufferData: Result["bufferData"] = []; let elapsed = 0; let stopped = 0; while (elapsed < duration) { sil.forEach(r => { const rate = 60 / ((pns.find(p => p.machine === r.id)?.silicone || r.cycle)); buffers[r.id] = Math.max(0, buffers[r.id] - rate * interval / 60) }); const eligible = pns.filter(p => p.active && remaining[p.pn] > 0).sort((a, b) => (buffers[a.machine] / (60 / a.silicone) - buffers[b.machine] / (60 / b.silicone)) || (remaining[b.pn] - remaining[a.pn]) || (a.priority - b.priority) || (a.silicone - b.silicone)); const pn = eligible[0]; if (pn) { const r = sil.find(x => x.id === pn.machine)!; const before = buffers[pn.machine]; const qty = Math.min(pn.max, Math.max(pn.min, Math.ceil((r.max! - before) / pn.stock) * pn.min), remaining[pn.pn]); const setup = orders.length && orders[orders.length - 1].pn !== pn.pn ? weld.setup : 0; const process = setup + qty * weld.cycle / 60; if (elapsed + process <= duration) { buffers[pn.machine] += qty; remaining[pn.pn] -= qty; orders.push({ no: orders.length + 1, pn: pn.pn, machine: pn.machine, qty, start: timeLabel(elapsed, start), end: timeLabel(elapsed + process, start), setup, served: pn.demand - remaining[pn.pn], remaining: remaining[pn.pn], before: Math.round(before), after: Math.round(buffers[pn.machine]), coverage: Math.round(buffers[pn.machine] / (60 / pn.silicone)) }); elapsed += Math.max(interval, process) } else { stopped += interval; elapsed += interval } } else { stopped += interval; elapsed += interval } bufferData.push({ time: timeLabel(elapsed, start), m600: Math.round(buffers["600k"] || 0), m1m: Math.round(buffers["1M"] || 0), total: Math.round((buffers["600k"] || 0) + (buffers["1M"] || 0)) }) }
 const totalDemand = pns.reduce((s, p) => s + p.demand, 0); const served = pns.reduce((s, p) => s + p.demand - remaining[p.pn], 0); const metrics = { avgBuffer: Math.round(bufferData.reduce((s, x) => s + x.total, 0) / Math.max(1, bufferData.length)), maxBuffer: Math.max(0, ...bufferData.map(x => x.total)), weldUtil: Math.min(100, Math.round((orders.reduce((s, o) => s + o.qty * weld.cycle / 60 + o.setup, 0) / weld.available / weld.machines) * 100)), unmet: totalDemand - served, leadTime: orders.length ? Math.round((orders[orders.length - 1].end.split(":")[0] as unknown as number) || duration) : 0, bottleneck: sil.sort((a, b) => (a.available * a.machines) - (b.available * b.machines))[0]?.name || "N/A", stopped, setups: orders.filter(o => o.setup > 0).length }; const alerts = [...(metrics.unmet > 0 ? ["A demanda não pode ser totalmente atendida no turno."] : []), ...(stopped ? ["Uma máquina ficou sem peças em parte do turno."] : []), ...(bufferData.some(x => x.m600 > (sil.find(r => r.id === "600k")?.max || Infinity) || x.m1m > (sil.find(r => r.id === "1M")?.max || Infinity)) ? ["Um buffer ultrapassou o limite máximo."] : []), ...(!orders.length ? ["Não existe PN elegível para abastecer uma máquina."] : [])]; const next = { orders, metrics, alerts, bufferData }; setResult(next); localStorage.setItem("damper-last-result", JSON.stringify(next)) }
 return <div className="page-content"><div className="intro"><div><p className="eyebrow">PESQUISA OPERACIONAL · SIMULAÇÃO CRONOLÓGICA</p><h2>Simulação de abastecimento</h2><p className="muted">A cada intervalo, o motor consome buffers, escolhe a máquina mais urgente e gera lotes respeitando capacidade e regras dos PNs.</p></div><button className="primary-button" onClick={run}><Play /> Executar simulação</button></div><Section title="Parâmetros do turno"><div className="form-grid"><Field label="Duração do turno (min)" value={duration} onChange={v => setDuration(Number(v))} /><Field label="Horário inicial" value={start} type="time" onChange={setStart} /><Field label="Intervalo de cálculo (min)" value={interval} onChange={v => setInterval(Number(v))} /><Field label="Estratégia" value={strategy} options={["Menor cobertura primeiro", "Maior demanda pendente"]} onChange={setStrategy} /></div></Section>{result && <><div className="simulation-kpis"><div><span>Ordens calculadas</span><strong>{result.orders.length} lotes</strong></div><div><span>Demanda atendida</span><strong>{result.metrics.unmet === 0 ? "100%" : `${Number(result.metrics.unmet)} não atendidas`}</strong></div><div><span>Setups</span><strong>{result.metrics.setups}</strong></div><div><span>Parada por falta</span><strong>{result.metrics.stopped} min</strong></div></div><Section title="Sequência cronológica" subtitle="A última execução é utilizada no Dashboard" action={<button className="outline-button small" onClick={() => { setResult(null); localStorage.removeItem("damper-last-result") }}>Limpar resultados</button>}><div className="sequence-table simulation-table"><div className="table-row table-head"><span># / PN</span><span>Destino</span><span>Lote</span><span>Início — fim</span><span>Setup</span><span>Buffer antes — depois</span></div>{result.orders.map(o => <div className="table-row" key={o.no}><span className="strong-cell">{o.no} · {o.pn}</span><span>{o.machine}</span><span>{o.qty}</span><span>{o.start} — {o.end}</span><span>{o.setup} min</span><span>{o.before} — {o.after} ({o.coverage} min)</span></div>)}</div></Section></>}</div> }

function Registry({ pns, setPns }: { pns: PN[]; setPns: (p: PN[]) => void }) { const [draft, setDraft] = useState<PN>({ pn: "", desc: "", demand: 0, machine: "600k", weld: 30, silicone: 120, min: 12, max: 36, stock: 0, priority: 1, active: true }); const add = () => { if (!draft.pn) return; setPns([...pns, draft]); setDraft({ ...draft, pn: "", desc: "" }) }; return <div className="page-content"><div className="intro"><div><p className="eyebrow">MESTRE DE DADOS</p><h2>Cadastro de PNs</h2><p className="muted">Todos os parâmetros abaixo são usados pelo motor de simulação.</p></div><button className="primary-button" onClick={add}>+ Adicionar PN</button></div><Section title="Novo PN"><div className="form-grid pn-form"><Field label="Código do PN" value={draft.pn} type="text" onChange={v => setDraft({ ...draft, pn: v })} /><Field label="Descrição" value={draft.desc} type="text" onChange={v => setDraft({ ...draft, desc: v })} /><Field label="Demanda do período" value={draft.demand} onChange={v => setDraft({ ...draft, demand: +v })} /><Field label="Máquina de silicone" value={draft.machine} options={["600k", "1M"]} onChange={v => setDraft({ ...draft, machine: v as PN["machine"] })} /><Field label="Solda (s)" value={draft.weld} onChange={v => setDraft({ ...draft, weld: +v })} /><Field label="Silicone (s)" value={draft.silicone} onChange={v => setDraft({ ...draft, silicone: +v })} /><Field label="Lote mínimo" value={draft.min} onChange={v => setDraft({ ...draft, min: +v })} /><Field label="Lote máximo" value={draft.max} onChange={v => setDraft({ ...draft, max: +v })} /><Field label="Estoque inicial após solda" value={draft.stock} onChange={v => setDraft({ ...draft, stock: +v })} /><Field label="Prioridade" value={draft.priority} onChange={v => setDraft({ ...draft, priority: +v })} /></div></Section><Section title={`${pns.length} PNs cadastrados`}><div className="sequence-table pn-table"><div className="table-row table-head"><span>PN</span><span>Descrição</span><span>Demanda</span><span>Destino</span><span>Estoque</span><span>Status</span></div>{pns.map((p, i) => <div className="table-row" key={`${p.pn}-${i}`}><span className="strong-cell">{p.pn}</span><span>{p.desc}</span><span>{p.demand}</span><span>{p.machine}</span><span>{p.stock}</span><span>{p.active ? "Ativo" : "Inativo"}</span></div>)}</div></Section></div> }

function Resources({ resources, setResources }: { resources: Resource[]; setResources: (r: Resource[]) => void }) { const update = (id: string, key: keyof Resource, value: string) => setResources(resources.map(r => r.id === id ? { ...r, [key]: key === "name" ? value : Number(value) } : r)); return <div className="page-content"><div className="intro"><div><p className="eyebrow">MESTRE DE DADOS</p><h2>Cadastro de Recursos</h2><p className="muted">Disponibilidade, ciclos, buffers e quantidade de máquinas.</p></div></div>{resources.map(r => <Section key={r.id} title={r.name} subtitle={r.kind === "weld" ? "Recurso de solda" : "Recurso de silicone"}><div className="form-grid resource-form"><Field label="Tempo disponível por turno (min)" value={r.available} onChange={v => update(r.id, "available", v)} /><Field label="Tempo de ciclo (s/peça)" value={r.cycle} onChange={v => update(r.id, "cycle", v)} /><Field label="Quantidade de máquinas" value={r.machines} onChange={v => update(r.id, "machines", v)} />{r.kind === "weld" ? <Field label="Setup entre PNs (min)" value={r.setup} onChange={v => update(r.id, "setup", v)} /> : <><Field label="Estoque inicial" value={r.initial || 0} onChange={v => update(r.id, "initial", v)} /><Field label="Buffer mínimo" value={r.min || 0} onChange={v => update(r.id, "min", v)} /><Field label="Buffer máximo" value={r.max || 0} onChange={v => update(r.id, "max", v)} /></>}</div></Section>)}</div> }

void Settings2
void useMemo
void Gauge
void PackageCheck
void ClipboardList
void ArrowUpRight
void BarChart3
void Layers3
void Sparkles
void Timer
void Factory
void Truck
void Bell
void ChevronDown
void Menu
void X
void Activity
void AlertTriangle
void Target
void Play
